import type { UIMessage } from "ai";
import { isContextSummaryMessage } from "../components/chat/chat-context-summary-card";

/**
 * Approximate context window size in characters.
 * Based on ~128k tokens * ~4 chars per token.
 */
const CONTEXT_WINDOW_CHARS = 128 * 1024 * 4; // ~524k chars

interface ContextEstimate {
  /** Total estimated characters in context */
  estimatedChars: number;
  /** Usage percentage (0-100) */
  percentage: number;
  /** Formatted display string like "123k 42% context" */
  displayText: string;
}

/**
 * Extracts text content from all parts of a message.
 */
export function collectMessageText(message: UIMessage): string {
  return message.parts
    .map((part) => (part.type === "text" ? part.text : ""))
    .filter((segment) => segment.length > 0)
    .join("\n");
}

/**
 * Estimates context usage from a list of UI messages.
 * 
 * Excludes Lightcode context summary system messages since those are
 * generated by the context compaction system and shouldn't count
 * against the estimate.
 * 
 * @param messages - The current list of UI messages
 * @returns Context estimate with usage percentage and display text
 */
export function estimateContextUsage(messages: UIMessage[]): ContextEstimate {
  const totalChars = messages
    .filter((msg) => !isContextSummaryMessage(msg))
    .reduce((sum, msg) => sum + collectMessageText(msg).length, 0);

  const percentage = Math.min(100, Math.round((totalChars / CONTEXT_WINDOW_CHARS) * 100));

  // Format: "123k 42% context" - show kilobytes if large enough
  const displayText =
    totalChars >= 10000
      ? `${Math.round(totalChars / 1000)}k ${percentage}% context`
      : `${totalChars} ${percentage}% context`;

  return {
    estimatedChars: totalChars,
    percentage,
    displayText,
  };
}
